'use strict';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>v==null?'--':new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(v);
const dec=v=>v==null?'--':new Intl.NumberFormat('en-US',{maximumFractionDigits:1}).format(v);
const pct=v=>v==null?'--':new Intl.NumberFormat('en-US',{style:'percent',maximumFractionDigits:1}).format(v);
const label=v=>v==null?'--':String(v).replaceAll('_',' ');
const date=v=>v?new Date(v).toLocaleDateString('en-US',{year:'numeric',month:'short',day:'numeric',timeZone:'UTC'}):'--';
let pack,system,groups=[],population=[],populationById=new Map(),referenceByItem=new Map(),tab='system',query='',account='',hook='',angle='',format='',product='',sort='rank';
let selected=new Set();
const comparing=new Set();

function itemPreview(item){const u=item?.preview?.thumbnail_url;return u?`<img loading="lazy" src="${esc(u)}" alt="">`:'<div class="empty-media">No preview</div>'}
function itemKeyFromReference(r){return r?.item_id||r?.reference_id||''}
function selectedItems(){return [...selected].map(id=>populationById.get(id)).filter(Boolean)}
function selectionSummary(){
  const rows=selectedItems(),countBy=k=>rows.reduce((m,r)=>{const v=k(r)||'unknown';m[v]=(m[v]||0)+1;return m},{});
  const accounts=countBy(r=>r.source?.account),groupsMap=countBy(r=>r.group_id),langs=countBy(r=>r.creative?.language);
  const largest=obj=>{const vals=Object.values(obj);return rows.length&&vals.length?Math.max(...vals)/rows.length:0};
  return {rows,accounts,groupsMap,langs,largestAccount:largest(accounts),largestGroup:largest(groupsMap)};
}
function mediaUrls(r){const m=r.media||{};return m.slide_paths?.length?m.slide_paths:m.slide_urls?.length?m.slide_urls:[m.cover_path||m.thumbnail_url].filter(Boolean)}
function media(r,large=false){const m=r.media||{},urls=mediaUrls(r);if(m.video_path||m.video_url)return `<video controls preload="none" src="${esc(m.video_path||m.video_url)}"></video>`;if(!urls.length)return '<div class="empty-media">No media</div>';return `<div class="slides ${large?'large':''}">${urls.map((u,i)=>`<img loading="lazy" src="${esc(u)}" alt="Slide ${i+1}">`).join('')}</div>`}
function badge(v){return v?`<span class="badge">${esc(label(v))}</span>`:''}
function metric(name,value,sub=''){return `<div class="metric"><small>${esc(name)}</small><strong>${value}</strong><span>${esc(sub)}</span></div>`}

function coverageStatus(){
  const s=system.selection||{};
  const good=(s.account_coverage??0)>=1&&((s.max_account_share??1)<=0.25||s.references<8);
  return `<div class="coverage ${good?'coverage-ok':'coverage-warn'}"><b>${good?'Representative sample coverage':'Selection coverage needs attention'}</b><span>Strategy ${esc(label(s.strategy))} · accounts ${num(s.accounts_represented)}/${num(s.accounts_total)} · largest account ${pct(s.max_account_share)}</span></div>`
}
function accountBars(){
  const rows=system.accounts||[],max=Math.max(1,...rows.map(r=>r.selected_references||0));
  return `<div class="bar-list">${rows.map(r=>`<div class="bar-item"><span><b>${esc(r.account)}</b><small>${num(r.posts)} posts · ${num(r.population_posts)} in reference population</small></span><div class="bar-track"><div class="bar-fill" style="width:${(r.selected_references||0)/max*100}%"></div></div><strong>${num(r.selected_references)} refs</strong></div>`).join('')}</div>`
}
function dimensionBlock(key,rows){
  const top=(rows||[]).slice(0,8),max=Math.max(1,...top.map(r=>r.posts||0));
  return `<section class="panel"><h3>${esc(label(key))}</h3>${top.map(r=>`<div class="dim-row"><span><b>${esc(label(r.value))}</b><small>n=${num(r.posts)} · ${num(r.accounts)} accounts</small></span><div class="bar-track"><div class="bar-fill" style="width:${(r.posts||0)/max*100}%"></div></div><span>top25 ${pct(r.top25_rate)}<small>save ${pct(r.median_save_rate)}</small></span></div>`).join('')}</section>`
}
function systemView(){
  const d=system.dataset||{},p=system.performance||{},rp=system.reference_population||{},s=system.selection||{},dims=system.dimensions||{};
  const dimKeys=['hook_technique','content_angle','content_format','product_placement_style','cta_type','primary_language_code'];
  return `<section class="intro"><h1>Whole-system map</h1><p>Start with the complete observed operator system. The reference sample exists only to inspect representative executions after the system shape is visible.</p></section>
  <div class="metric-grid">${metric('Posts',num(d.posts),'full observed dataset')}${metric('Accounts',num(d.accounts),'same operator portfolio')}${metric('Reference population',num(rp.posts),esc(label(rp.content_type)))}${metric('Suggested',num(s.references),'representative executions')}${metric('Median views',num(p.median_views))}${metric('P95 views',num(p.p95_views))}${metric('Median save rate',pct(p.median_save_rate))}${metric('Date range',`${date(d.date_min)} → ${date(d.date_max)}`)}</div>
  ${coverageStatus()}
  <div class="system-grid"><section class="panel"><h2>Account coverage</h2><p>The UI shows how much of the reference sample comes from each channel so strong accounts cannot silently dominate the research.</p>${accountBars()}</section><section class="panel"><h2>Operating shape</h2><p><b>Content mix</b></p>${Object.entries(d.content_types||{}).map(([k,v])=>`<p>${esc(label(k))}: <b>${num(v)}</b></p>`).join('')}<p><b>Selection strategy</b></p><p>${esc(label(s.strategy))}: cover accounts first, then trade off performance, structural novelty, and account balance.</p></section></div>
  <h2 class="section-title">Creative system dimensions</h2><div class="dimension-grid">${dimKeys.filter(k=>dims[k]?.length).map(k=>dimensionBlock(k,dims[k])).join('')}</div>`
}
function accountsView(){
  const rows=system.accounts||[];
  return `<section class="intro"><h1>Account roles & cadence</h1><p>All accounts belong to the same operator. Compare channel behavior without treating accounts as independent validation.</p></section><div class="table"><table><thead><tr><th>Account</th><th>Posts</th><th>Ref-pop posts</th><th>Selected refs</th><th>Active days</th><th>Median/day</th><th>Max/day</th><th>Median views</th><th>Top25</th><th>P95 breakout</th><th>Save</th><th>First → last</th></tr></thead><tbody>${rows.map(r=>`<tr><td><b>${esc(r.account)}</b></td><td>${num(r.posts)}</td><td>${num(r.population_posts)}</td><td>${num(r.selected_references)}</td><td>${num(r.active_days)}</td><td>${dec(r.median_posts_per_active_day)}</td><td>${num(r.max_posts_per_day)}</td><td>${num(r.median_views)}</td><td>${pct(r.top25_rate)}</td><td>${pct(r.global_p95_rate)}</td><td>${pct(r.median_save_rate)}</td><td>${date(r.first_post)} → ${date(r.last_post)}</td></tr>`).join('')}</tbody></table></div>`
}
function structuresView(){
  return `<section class="intro"><h1>Structures across the full population</h1><p>These groups use the entire reference population, not just selected examples. They are descriptive structures, not downstream creative families.</p></section><div class="group-list">${groups.map(g=>`<button class="group" data-group="${esc(g.group_id)}"><b>${esc(g.group_id)}</b><span>${esc(label(g.hook_technique))} / ${esc(label(g.content_angle))} / ${esc(label(g.content_format))} / ${esc(label(g.product_placement_style))}</span><span>n=${num(g.posts)} · ${num(g.accounts)} accounts · refs ${num(g.selected_references)} · top25 ${pct(g.top25_rate)} · P95 ${pct(g.global_p95_rate)} · save ${pct(g.median_save_rate)}</span></button>`).join('')}</div>`
}

function groupDetail(g){
  const members=g.members||[],refs=g.reference_ids||[];
  const refRows=refs.map(id=>pack.references.find(r=>r.reference_id===id)).filter(Boolean);
  const selectedInGroup=members.filter(m=>selected.has(m.item_id)).length;
  return `<div class="drawer-bg" id="group-drawer-bg"><aside class="drawer group-drawer"><button id="group-close">Close</button>
  <h2>${esc(g.group_id)}</h2>
  <p><b>Full population: n=${num(g.posts)}</b> across ${num(g.accounts)} accounts. Suggested examples: <b>${num(refs.length)}</b>. You selected: <b>${num(selectedInGroup)}</b>.</p>
  <div class="badges">${badge(g.hook_technique)}${badge(g.content_angle)}${badge(g.content_format)}${badge(g.product_placement_style)}</div>
  <div class="stats"><span><b>${pct(g.top25_rate)}</b>top25</span><span><b>${pct(g.global_p95_rate)}</b>P95 breakout</span><span><b>${num(g.median_views)}</b>median views</span><span><b>${pct(g.median_save_rate)}</b>save</span></div>
  <h3>Suggested examples</h3>
  <p>${refs.length?'Quick visual scan of the system-suggested examples. You can select any post below, not only these.':'No suggested example from this group is in the current sample.'}</p>
  <div class="group-ref-grid">${refRows.map(r=>`<article class="group-ref-card"><button class="group-ref-open" data-open-item="${esc(itemKeyFromReference(r))}"><div class="group-ref-media">${media(r)}</div><span><b>${esc(r.reference_id)}</b><small>${esc(r.source?.account||'')} · ${num(r.performance?.views)} views</small></span></button><label><input type="checkbox" data-select-item="${esc(itemKeyFromReference(r))}" ${selected.has(itemKeyFromReference(r))?'checked':''}> Select</label></article>`).join('')}</div>
  <div class="group-toolbar"><button data-select-suggested="${esc(g.group_id)}">Select suggested</button><button data-clear-group="${esc(g.group_id)}">Clear group selection</button></div>
  <h3>All ${num(members.length)} posts in this group</h3>
  <div class="table"><table><thead><tr><th>Select</th><th>Preview</th><th>Rank</th><th>Account</th><th>Views</th><th>Account pct</th><th>Global pct</th><th>Save</th><th>Hook</th><th>Inspect</th><th>Original</th></tr></thead><tbody>
  ${members.map(m=>`<tr class="${selected.has(m.item_id)?'selected-row':''}"><td><input type="checkbox" data-select-item="${esc(m.item_id)}" ${selected.has(m.item_id)?'checked':''}></td><td><button class="thumb-button" data-open-item="${esc(m.item_id)}">${m.thumbnail_url?`<img class="member-thumb" loading="lazy" src="${esc(m.thumbnail_url)}" alt="">`:'<div class="member-thumb empty-thumb">—</div>'}</button></td><td>#${num(m.rank_position)}</td><td>${esc(m.account||'')}</td><td>${num(m.views)}</td><td>${pct(m.account_views_pct)}</td><td>${pct(m.global_views_pct)}</td><td>${pct(m.save_rate)}</td><td class="wrap-cell">${esc(m.hook_text||m.topic||'')}</td><td><button data-open-item="${esc(m.item_id)}">${m.reference_id?esc(m.reference_id):'Inspect'}</button></td><td>${m.url?`<a href="${esc(m.url)}" target="_blank" rel="noopener">Open</a>`:'--'}</td></tr>`).join('')}
  </tbody></table></div></aside></div>`
}

function card(r){const id=r.reference_id,itemId=itemKeyFromReference(r),p=r.performance||{},c=r.creative||{},b=r.blueprint||{};return `<article class="card"><div class="visual">${media(r)}</div><div class="body"><div class="row"><b>${esc(id)}</b><span>#${num(r.selection?.rank_position)} · ${esc(label(r.selection?.reason))}</span></div><h3>${esc(c.hook?.text||c.topic||'Untitled reference')}</h3><p class="source">${esc(r.source?.account||'')} · ${date(r.source?.created_at)}</p><div class="stats"><span><b>${pct(p.account_views_pct)}</b>account pct</span><span><b>${num(p.views)}</b>views</span><span><b>${pct(p.save_rate)}</b>save</span></div><div class="badges">${badge(c.hook?.technique)}${badge(c.angle)}${badge(c.content_format)}${badge(b.product_placement_style)}</div><div class="actions"><button data-open-item="${esc(itemId)}">Inspect</button><label><input type="checkbox" data-select-item="${esc(itemId)}" ${selected.has(itemId)?'checked':''}> Select</label><label><input type="checkbox" data-compare="${id}" ${comparing.has(id)?'checked':''}> Compare</label></div></div></article>`}
function options(values,current,title){return `<option value="">${title}</option>${[...new Set(values.filter(Boolean))].sort().map(v=>`<option value="${esc(v)}" ${v===current?'selected':''}>${esc(label(v))}</option>`).join('')}`}
function filtered(){let rows=pack.references.filter(r=>(!query||JSON.stringify(r).toLowerCase().includes(query.toLowerCase()))&&(!account||r.source?.account===account)&&(!hook||r.creative?.hook?.technique===hook)&&(!angle||r.creative?.angle===angle)&&(!format||r.creative?.content_format===format)&&(!product||r.product?.placement_style===product));return rows.sort((a,b)=>sort==='views'?(b.performance?.views??-1)-(a.performance?.views??-1):sort==='save'?(b.performance?.save_rate??-1)-(a.performance?.save_rate??-1):(a.selection?.rank_position??9999)-(b.selection?.rank_position??9999))}
function filters(){const r=pack.references;return `<div class="filters"><input id="search" placeholder="Search hook, topic, labels..." value="${esc(query)}"><select id="account">${options(r.map(x=>x.source?.account),account,'All accounts')}</select><select id="hook">${options(r.map(x=>x.creative?.hook?.technique),hook,'All hooks')}</select><select id="angle">${options(r.map(x=>x.creative?.angle),angle,'All angles')}</select><select id="format">${options(r.map(x=>x.creative?.content_format),format,'All formats')}</select><select id="product">${options(r.map(x=>x.product?.placement_style),product,'All product timing')}</select><select id="sort"><option value="rank" ${sort==='rank'?'selected':''}>Performance rank</option><option value="views" ${sort==='views'?'selected':''}>Views</option><option value="save" ${sort==='save'?'selected':''}>Save rate</option></select></div>`}
function referencesView(){const rows=filtered();return `<section class="intro"><h1>Suggested examples</h1><p>These are system-suggested examples to inspect first. You can also select any post from a Structure group, even when it is not suggested here.</p></section>${filters()}<p>${rows.length} matching suggestions</p><div class="grid">${rows.map(card).join('')}</div>`}

const compareFields=[['Account',r=>r.source?.account],['Hook',r=>r.creative?.hook?.technique],['Angle',r=>r.creative?.angle],['Format',r=>r.creative?.content_format],['Slides',r=>r.creative?.slide_count],['Sequence',r=>(r.blueprint?.sequence_roles||[]).join(' -> ')],['Product',r=>r.product?.placement_style],['Product first',r=>r.product?.first_position],['CTA',r=>r.cta?.type],['CTA position',r=>r.cta?.position],['Visual',r=>r.visual?.dominant_type],['Account pct',r=>pct(r.performance?.account_views_pct)],['Save rate',r=>pct(r.performance?.save_rate)]];
function compareView(){const rows=pack.references.filter(r=>comparing.has(r.reference_id)).slice(0,4);if(!rows.length)return '<section class="intro"><h1>Compare</h1><p>Select 2–4 representative references first.</p></section>';const common=compareFields.filter(([_,fn])=>{const v=rows.map(fn);return v[0]!=null&&v.every(x=>JSON.stringify(x)===JSON.stringify(v[0]))});return `<section class="intro"><h1>Compare ${rows.length}</h1><p>Separate common mechanism from implementation details before promoting a family.</p></section><div class="compare-media">${rows.map(r=>`<div><b>${r.reference_id}</b><small>${esc(r.source?.account||'')}</small>${media(r)}</div>`).join('')}</div><div class="table"><table><thead><tr><th>Field</th>${rows.map(r=>`<th>${r.reference_id}</th>`).join('')}</tr></thead><tbody>${compareFields.map(([n,fn])=>`<tr class="${common.some(([x])=>x===n)?'common':''}"><th>${n}</th>${rows.map(r=>`<td>${esc(label(fn(r)))}</td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="common-box"><b>Exact common structure</b>${common.length?common.map(([n,fn])=>`<p>✓ ${n}: ${esc(label(fn(rows[0])))}</p>`).join(''):'<p>No exact common fields across this set.</p>'}</div>`}
function itemCard(item){const p=item.performance||{},c=item.creative||{};return `<article class="selected-card"><button class="selected-preview" data-open-item="${esc(item.item_id)}">${itemPreview(item)}</button><div><div class="row"><b>${esc(item.item_id)}</b><span>${item.reference_id?esc(item.reference_id):'full population'}</span></div><h3>${esc(c.hook?.text||c.topic||'Untitled')}</h3><p class="source">${esc(item.source?.account||'')} · ${esc(item.group_id||'ungrouped')}</p><div class="stats"><span><b>${num(p.views)}</b>views</span><span><b>${pct(p.account_views_pct)}</b>account pct</span><span><b>${pct(p.save_rate)}</b>save</span></div><div class="actions"><button data-open-item="${esc(item.item_id)}">Inspect</button><label><input type="checkbox" data-select-item="${esc(item.item_id)}" checked> Selected</label></div></div></article>`}
function selectedView(){const s=selectionSummary(),rows=s.rows,warnings=[];if(s.largestGroup>0.6&&rows.length>3)warnings.push(`Largest group is ${pct(s.largestGroup)} of selection`);if(s.largestAccount>0.5&&rows.length>3)warnings.push(`Largest account is ${pct(s.largestAccount)} of selection`);return `<section class="intro"><h1>Selected for Creative Bank</h1><p>${rows.length} posts · ${Object.keys(s.groupsMap).length} groups · ${Object.keys(s.accounts).length} accounts.</p><button id="export-selected" class="primary" ${rows.length?'':'disabled'}>Export selected.json</button></section><div class="selection-audit">${warnings.length?warnings.map(w=>`<p>⚠ ${esc(w)}</p>`).join(''):'<p>Selection coverage looks reasonably spread. This is a warning aid, not proof of representativeness.</p>'}<p>Languages: ${esc(Object.entries(s.langs).map(([k,v])=>`${k} ${v}`).join(' · ')||'--')}</p></div><div class="selected-grid">${rows.map(itemCard).join('')}</div>`}
function populationDetail(item){const c=item.creative||{},p=item.performance||{},b=item.blueprint||{};return `<div class="drawer-bg" id="item-drawer-bg"><aside class="drawer"><button id="item-close">Close</button><h2>${esc(item.item_id)}</h2><p>${esc(item.source?.account||'')} · ${esc(item.group_id||'ungrouped')} · ${item.reference_id?esc(item.reference_id):'not in Suggested'}</p><div class="population-preview">${itemPreview(item)}</div><h3>${esc(c.hook?.text||'')}</h3><div class="stats"><span><b>${pct(p.account_views_pct)}</b>account pct</span><span><b>${num(p.views)}</b>views</span><span><b>${pct(p.save_rate)}</b>save</span></div><h3>Blueprint</h3><dl>${Object.entries(b).filter(([_,v])=>v!=null&&v!=='').map(([k,v])=>`<dt>${esc(label(k))}</dt><dd>${esc(Array.isArray(v)?v.join(' -> '):label(v))}</dd>`).join('')}</dl><h3>Slide sequence</h3><div class="sequence">${(item.sequence||[]).map(s=>`<div><b>${num(s.position)} / ${esc(label(s.role))}</b><p>${esc(s.primary_text||'')}</p><small>${esc(label(s.visual_type))} / ${esc(s.visual_description||'')}</small></div>`).join('')}</div><div class="actions"><label><input type="checkbox" data-select-item="${esc(item.item_id)}" ${selected.has(item.item_id)?'checked':''}> Select for Creative Bank</label></div><p><a href="${esc(item.source?.url||'#')}" target="_blank" rel="noopener">View original</a></p></aside></div>`}
function openItem(itemId){const ref=referenceByItem.get(itemId);if(ref){document.querySelector('#group-drawer-bg')?.remove();document.body.insertAdjacentHTML('beforeend',detail(ref));$('#close').onclick=()=>$('#drawer-bg').remove();$('#drawer-bg').onclick=e=>{if(e.target.id==='drawer-bg')e.currentTarget.remove()};wireSelectionControls();return}const item=populationById.get(itemId);if(!item)return;document.body.insertAdjacentHTML('beforeend',populationDetail(item));$('#item-close').onclick=()=>$('#item-drawer-bg').remove();$('#item-drawer-bg').onclick=e=>{if(e.target.id==='item-drawer-bg')e.currentTarget.remove()};wireSelectionControls()}
function openReference(id){const r=pack.references.find(x=>x.reference_id===id);if(r)openItem(itemKeyFromReference(r))}

function openReference(id){const r=pack.references.find(x=>x.reference_id===id);if(!r)return;document.querySelector('#group-drawer-bg')?.remove();document.body.insertAdjacentHTML('beforeend',detail(r));$('#close').onclick=()=>$('#drawer-bg').remove();$('#drawer-bg').onclick=e=>{if(e.target.id==='drawer-bg')e.currentTarget.remove()}}
function detail(r){const c=r.creative||{},p=r.performance||{},b=r.blueprint||{};return `<div class="drawer-bg" id="drawer-bg"><aside class="drawer"><button id="close">Close</button><h2>${r.reference_id}</h2><p>${esc(r.source?.account||'')} · performance rank #${num(r.selection?.rank_position)} · ${esc(label(r.selection?.reason))}</p>${media(r,true)}<h3>${esc(c.hook?.text||'')}</h3><div class="stats"><span><b>${pct(p.account_views_pct)}</b>account pct</span><span><b>${num(p.views)}</b>views</span><span><b>${pct(p.save_rate)}</b>save</span></div><h3>Blueprint</h3><dl>${Object.entries(b).filter(([_,v])=>v!=null&&v!=='').map(([k,v])=>`<dt>${esc(label(k))}</dt><dd>${esc(Array.isArray(v)?v.join(' -> '):label(v))}</dd>`).join('')}</dl><h3>Slide sequence</h3><div class="sequence">${(r.sequence||[]).map(s=>`<div><b>${num(s.position)} / ${esc(label(s.role))}</b><p>${esc(s.primary_text||'')}</p><small>${esc(label(s.visual_type))} / ${esc(s.visual_description||'')}</small></div>`).join('')}</div><p><a href="${esc(r.source?.url||'#')}" target="_blank" rel="noopener">View original</a></p></aside></div>`}

function storageKey(){return 'cr-selected:'+String(pack?.pack_id||pack?.reference_schema_version||'default')}
function save(){localStorage.setItem(storageKey(),JSON.stringify([...selected]))}
function exportSelection(){const blob=new Blob([JSON.stringify({reference_pack:pack.pack_id,reference_schema_version:pack.reference_schema_version,selection_type:'population_items',selected:[...selected]},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='selected.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function wireSelectionControls(){document.querySelectorAll('[data-select-item]').forEach(x=>x.onchange=()=>{x.checked?selected.add(x.dataset.selectItem):selected.delete(x.dataset.selectItem);save();renderCounts();renderSelectionBar()})}
function wire(){document.querySelectorAll('[data-open-item]').forEach(b=>b.onclick=()=>openItem(b.dataset.openItem));wireSelectionControls();document.querySelectorAll('[data-compare]').forEach(x=>x.onchange=()=>{if(x.checked&&comparing.size>=4){x.checked=false;return}x.checked?comparing.add(x.dataset.compare):comparing.delete(x.dataset.compare);renderCounts()});['search','account','hook','angle','format','product','sort'].forEach(id=>{const e=$('#'+id);if(e)e.oninput=e.onchange=()=>{if(id==='search')query=e.value;if(id==='account')account=e.value;if(id==='hook')hook=e.value;if(id==='angle')angle=e.value;if(id==='format')format=e.value;if(id==='product')product=e.value;if(id==='sort')sort=e.value;render()}});document.querySelectorAll('[data-group]').forEach(b=>b.onclick=()=>{const g=groups.find(x=>x.group_id===b.dataset.group);if(!g)return;document.body.insertAdjacentHTML('beforeend',groupDetail(g));$('#group-close').onclick=()=>$('#group-drawer-bg').remove();$('#group-drawer-bg').onclick=e=>{if(e.target.id==='group-drawer-bg')e.currentTarget.remove()};wire();document.querySelectorAll('[data-select-suggested]').forEach(x=>x.onclick=()=>{const group=groups.find(g=>g.group_id===x.dataset.selectSuggested);(group?.members||[]).filter(m=>m.reference_id).forEach(m=>selected.add(m.item_id));save();$('#group-drawer-bg')?.remove();renderCounts();renderSelectionBar()});document.querySelectorAll('[data-clear-group]').forEach(x=>x.onclick=()=>{const group=groups.find(g=>g.group_id===x.dataset.clearGroup);(group?.members||[]).forEach(m=>selected.delete(m.item_id));save();$('#group-drawer-bg')?.remove();renderCounts();renderSelectionBar()})});$('#export-selected')?.addEventListener('click',exportSelection)}
function renderSelectionBar(){let bar=$('#selection-bar');if(!bar){document.body.insertAdjacentHTML('beforeend','<div id="selection-bar" class="selection-bar"></div>');bar=$('#selection-bar')}const s=selectionSummary();bar.innerHTML=`<span><b>Selected ${s.rows.length}</b> · ${Object.keys(s.groupsMap).length} groups · ${Object.keys(s.accounts).length} accounts</span><span><button id="review-selected">Review selected</button><button id="clear-selected">Clear</button></span>`;$('#review-selected').onclick=()=>{tab='selected';render()};$('#clear-selected').onclick=()=>{selected.clear();save();render()}}
function renderCounts(){$('#counts').textContent=`${num(system?.dataset?.posts)} posts · ${num(system?.dataset?.accounts)} accounts · ${pack?.references?.length||0} refs · Selected ${selected.size}`}
function render(){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$('#main').innerHTML=({system:systemView,accounts:accountsView,structures:structuresView,references:referencesView,compare:compareView,selected:selectedView}[tab])();wire();renderCounts();renderSelectionBar()}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});
Promise.all([fetch('workspace.json').then(r=>r.json()),fetch('population.json').then(r=>r.json()),fetch('system.json').then(r=>r.json()),fetch('candidate_groups.json').then(r=>r.json())]).then(([w,p,s,g])=>{pack=w;population=p.items||[];system=s;groups=g;populationById=new Map(population.map(item=>[item.item_id,item]));referenceByItem=new Map((pack.references||[]).filter(r=>r.item_id).map(r=>[r.item_id,r]));const stored=JSON.parse(localStorage.getItem(storageKey())||'[]');selected=new Set(stored.map(id=>id.startsWith('REF-')?(pack.references.find(r=>r.reference_id===id)?.item_id||id):id).filter(id=>populationById.has(id)));save();render()}).catch(e=>{$('#main').innerHTML=`<h1>Workspace unavailable</h1><pre>${esc(e.message)}</pre>`});
