'use strict';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>v==null?'--':new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(v);
const pct=v=>v==null?'--':new Intl.NumberFormat('en-US',{style:'percent',maximumFractionDigits:1}).format(v);
const label=v=>v==null?'--':String(v).replaceAll('_',' ');
let pack,groups=[],tab='references',query='',account='',hook='',angle='',format='',product='',sort='rank';
let selected=new Set();
const comparing=new Set();
function mediaUrls(r){const m=r.media||{};return m.slide_paths?.length?m.slide_paths:m.slide_urls?.length?m.slide_urls:[m.cover_path||m.thumbnail_url].filter(Boolean)}
function media(r,large=false){const m=r.media||{},urls=mediaUrls(r);if(m.video_path||m.video_url)return `<video controls preload="none" src="${esc(m.video_path||m.video_url)}"></video>`;if(!urls.length)return '<div class="empty-media">No media</div>';return `<div class="slides ${large?'large':''}">${urls.map((u,i)=>`<img loading="lazy" src="${esc(u)}" alt="Slide ${i+1}">`).join('')}</div>`}
function badge(v){return v?`<span class="badge">${esc(label(v))}</span>`:''}
function card(r){const id=r.reference_id,p=r.performance||{},c=r.creative||{},b=r.blueprint||{};return `<article class="card"><div class="visual">${media(r)}</div><div class="body"><div class="row"><b>${esc(id)}</b><span>#${num(r.selection?.rank_position)}</span></div><h3>${esc(c.hook?.text||c.topic||'Untitled reference')}</h3><div class="stats"><span><b>${pct(p.account_views_pct)}</b>account pct</span><span><b>${num(p.views)}</b>views</span><span><b>${pct(p.save_rate)}</b>save</span></div><div class="badges">${badge(c.hook?.technique)}${badge(c.angle)}${badge(c.content_format)}${badge(b.product_placement_style)}</div><div class="actions"><button data-open="${id}">Inspect</button><label><input type="checkbox" data-select="${id}" ${selected.has(id)?'checked':''}> Select</label><label><input type="checkbox" data-compare="${id}" ${comparing.has(id)?'checked':''}> Compare</label></div></div></article>`}
function options(values,current,title){return `<option value="">${title}</option>${[...new Set(values.filter(Boolean))].sort().map(v=>`<option value="${esc(v)}" ${v===current?'selected':''}>${esc(label(v))}</option>`).join('')}`}
function filtered(){let rows=pack.references.filter(r=>(!query||JSON.stringify(r).toLowerCase().includes(query.toLowerCase()))&&(!account||r.source?.account===account)&&(!hook||r.creative?.hook?.technique===hook)&&(!angle||r.creative?.angle===angle)&&(!format||r.creative?.content_format===format)&&(!product||r.product?.placement_style===product));return rows.sort((a,b)=>sort==='views'?(b.performance?.views??-1)-(a.performance?.views??-1):sort==='save'?(b.performance?.save_rate??-1)-(a.performance?.save_rate??-1):(a.selection?.rank_position??9999)-(b.selection?.rank_position??9999))}
function filters(){const r=pack.references;return `<div class="filters"><input id="search" placeholder="Search hook, topic, labels..." value="${esc(query)}"><select id="account">${options(r.map(x=>x.source?.account),account,'All accounts')}</select><select id="hook">${options(r.map(x=>x.creative?.hook?.technique),hook,'All hooks')}</select><select id="angle">${options(r.map(x=>x.creative?.angle),angle,'All angles')}</select><select id="format">${options(r.map(x=>x.creative?.content_format),format,'All formats')}</select><select id="product">${options(r.map(x=>x.product?.placement_style),product,'All product timing')}</select><select id="sort"><option value="rank" ${sort==='rank'?'selected':''}>Reference rank</option><option value="views" ${sort==='views'?'selected':''}>Views</option><option value="save" ${sort==='save'?'selected':''}>Save rate</option></select></div>`}
function references(){const rows=filtered();return `<section class="intro"><h1>Production references</h1><p>Inspect pixels and structure selected from the research dataset. Selection is evidence, not a causal claim.</p></section>${filters()}<p>${rows.length} matching references</p><div class="grid">${rows.map(card).join('')}</div>`}
function groupsView(){return `<section class="intro"><h1>Candidate structures</h1><p>Descriptive groupings only. Promote a group into a family downstream after inspection.</p></section><div class="group-list">${groups.map(g=>`<button class="group" data-group="${esc(g.group_id)}"><b>${esc(g.group_id)}</b><span>${esc(label(g.hook_technique))} / ${esc(label(g.content_angle))} / ${esc(label(g.content_format))} / ${esc(label(g.product_placement_style))}</span><span>n=${num(g.posts)} / ${num(g.accounts)} accounts / top25 ${pct(g.top25_rate)} / save ${pct(g.median_save_rate)}</span></button>`).join('')}</div>`}
const compareFields=[['Hook',r=>r.creative?.hook?.technique],['Angle',r=>r.creative?.angle],['Format',r=>r.creative?.content_format],['Slides',r=>r.creative?.slide_count],['Sequence',r=>(r.blueprint?.sequence_roles||[]).join(' -> ')],['Product',r=>r.product?.placement_style],['Product first',r=>r.product?.first_position],['CTA',r=>r.cta?.type],['CTA position',r=>r.cta?.position],['Visual',r=>r.visual?.dominant_type],['Account pct',r=>pct(r.performance?.account_views_pct)],['Save rate',r=>pct(r.performance?.save_rate)]];
function compareView(){const rows=pack.references.filter(r=>comparing.has(r.reference_id)).slice(0,4);if(!rows.length)return '<section class="intro"><h1>Compare</h1><p>Select 2-4 references from the References tab.</p></section>';const common=compareFields.filter(([_,fn])=>{const v=rows.map(fn);return v[0]!=null&&v.every(x=>JSON.stringify(x)===JSON.stringify(v[0]))});return `<section class="intro"><h1>Compare ${rows.length}</h1><p>Look for repeated structure before promoting a creative family.</p></section><div class="compare-media">${rows.map(r=>`<div><b>${r.reference_id}</b>${media(r)}</div>`).join('')}</div><div class="table"><table><thead><tr><th>Field</th>${rows.map(r=>`<th>${r.reference_id}</th>`).join('')}</tr></thead><tbody>${compareFields.map(([n,fn])=>`<tr class="${common.some(([x])=>x===n)?'common':''}"><th>${n}</th>${rows.map(r=>`<td>${esc(label(fn(r)))}</td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="common-box"><b>Common structure</b>${common.length?common.map(([n,fn])=>`<p>OK ${n}: ${esc(label(fn(rows[0])))}</p>`).join(''):'<p>No exact common fields across this set.</p>'}</div>`}
function selectedView(){const rows=pack.references.filter(r=>selected.has(r.reference_id));return `<section class="intro"><h1>Selected for production</h1><p>${rows.length} references ready for downstream family work.</p><button id="export-selected" class="primary">Export selected.json</button></section><div class="grid">${rows.map(card).join('')}</div>`}
function detail(r){const c=r.creative||{},p=r.performance||{},b=r.blueprint||{};return `<div class="drawer-bg" id="drawer-bg"><aside class="drawer"><button id="close">Close</button><h2>${r.reference_id}</h2>${media(r,true)}<h3>${esc(c.hook?.text||'')}</h3><div class="stats"><span><b>${pct(p.account_views_pct)}</b>account pct</span><span><b>${num(p.views)}</b>views</span><span><b>${pct(p.save_rate)}</b>save</span></div><h3>Blueprint</h3><dl>${Object.entries(b).filter(([_,v])=>v!=null&&v!=='').map(([k,v])=>`<dt>${esc(label(k))}</dt><dd>${esc(Array.isArray(v)?v.join(' -> '):label(v))}</dd>`).join('')}</dl><h3>Slide sequence</h3><div class="sequence">${(r.sequence||[]).map(s=>`<div><b>${num(s.position)} / ${esc(label(s.role))}</b><p>${esc(s.primary_text||'')}</p><small>${esc(label(s.visual_type))} / ${esc(s.visual_description||'')}</small></div>`).join('')}</div><p><a href="${esc(r.source?.url||'#')}" target="_blank" rel="noopener">View original</a></p></aside></div>`}
function storageKey(){return 'cr-selected:'+String(pack?.pack_id||pack?.reference_schema_version||'default')}
function save(){localStorage.setItem(storageKey(),JSON.stringify([...selected]))}
function exportSelection(){const blob=new Blob([JSON.stringify({reference_pack:pack.pack_id,reference_schema_version:pack.reference_schema_version,selected:[...selected]},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='selected.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function wire(){document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{const r=pack.references.find(x=>x.reference_id===b.dataset.open);document.body.insertAdjacentHTML('beforeend',detail(r));$('#close').onclick=()=>$('#drawer-bg').remove();$('#drawer-bg').onclick=e=>{if(e.target.id==='drawer-bg')e.currentTarget.remove()}});document.querySelectorAll('[data-select]').forEach(x=>x.onchange=()=>{x.checked?selected.add(x.dataset.select):selected.delete(x.dataset.select);save();renderCounts()});document.querySelectorAll('[data-compare]').forEach(x=>x.onchange=()=>{if(x.checked&&comparing.size>=4){x.checked=false;return}x.checked?comparing.add(x.dataset.compare):comparing.delete(x.dataset.compare);renderCounts()});['search','account','hook','angle','format','product','sort'].forEach(id=>{const e=$('#'+id);if(e)e.oninput=e.onchange=()=>{if(id==='search')query=e.value;if(id==='account')account=e.value;if(id==='hook')hook=e.value;if(id==='angle')angle=e.value;if(id==='format')format=e.value;if(id==='product')product=e.value;if(id==='sort')sort=e.value;render()}});document.querySelectorAll('[data-group]').forEach(b=>b.onclick=()=>{const g=groups.find(x=>x.group_id===b.dataset.group);hook=g.hook_technique==='<missing>'?'':g.hook_technique;angle=g.content_angle==='<missing>'?'':g.content_angle;format=g.content_format==='<missing>'?'':g.content_format;product=g.product_placement_style==='<missing>'?'':g.product_placement_style;tab='references';render()});$('#export-selected')?.addEventListener('click',exportSelection)}
function renderCounts(){$('#counts').textContent=`${pack?.references?.length||0} refs / Selected ${selected.size} / Compare ${comparing.size}`}
function render(){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$('#main').innerHTML=({references,groups:groupsView,compare:compareView,selected:selectedView}[tab])();wire();renderCounts()}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});
Promise.all([fetch('workspace.json').then(r=>r.json()),fetch('candidate_groups.json').then(r=>r.json())]).then(([w,g])=>{pack=w;groups=g;selected=new Set(JSON.parse(localStorage.getItem(storageKey())||'[]'));render()}).catch(e=>{$('#main').innerHTML=`<h1>Reference pack unavailable</h1><pre>${esc(e.message)}</pre>`});
